toml
[build.environment]
    API_ORIGIN_URL="VITE_APP_API_ORIGIN_URL"
    PROXY_SERVER_URL="VITE_APP_PROXY_SERVER_URL"

[[redirects]]
    from="API_ORIGIN_URL/*"
    to="PROXY_SERVER_URL/:splat"
    status="200"
